### ISSUE TITLE
Canonical links

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern-default-theme#543] opened 2019-12-17 17:34 UTC
### Is your feature request related to a problem?

No just a suggestion.

### What is the feature?

For canonical links you could add this simpler solution recommended by @bloatware:

    <link rel="canonical" href="<txp:page_url context trim="/" />">

Into all pages, never mind the context. Note the `trim` attribute needed here to reflect le current URL address scheme (for SEO).

**Comment by bloatware** [comment] 2019-12-17 17:49
Nope, `trim="/"` would be a bad idea for including in default theme. It would fail in some (new) permlink schemes.

**Comment by cara-tm** [comment] 2019-12-17 18:11
Oups. But without it I got some errors by SEO tools: non corresponding canonical URLs with addresses.

**Comment by philwareham** [comment] 2019-12-17 18:37
Which canonical exactly  is causing your SEO errors?

**Comment by cara-tm** [comment] 2019-12-17 19:12
All if I do not set the `trim` attribute.

**Comment by philwareham** [comment] 2019-12-18 10:02
I can't see what the problem is - I've check the canonical links on a live default theme and they are totally fine. If your issue is with ending `/` slash (not sure if that *is* your issue) that is *not* actually an issue and your SEO tools are wrong.

Quote from John Mueller at Google:

> "the slash after a hostname or domain name is irrelevant, you can use it or not when referring to the URL, it ends up being the same thing."

Basically, as long as you are consistent with your URL patterns and canonicals (which we are) then there is no issue.

**Comment by bloatware** [comment] 2019-12-18 10:37
Isn't it somehow related to [this](https://github.com/textpattern/textpattern/issues/929)?

**Comment by philwareham** [comment] 2019-12-18 10:39
Probably - but from memory and for legacy reasons didn't we choose to stick to current handling and make sure it was consistently generated by all tags?

**Comment by philwareham** [comment] 2019-12-18 10:41
Anyway, that isn't specific to the default theme. The default theme canonicals are generated consistently and correctly. If the issue you mention is worth discussing again, it needs to be in the core Textpattern repo not here. Thanks.

**Comment by bloatware** [comment] 2019-12-18 11:57
I guess @cara-tm meant that something like
```
<link rel="canonical" href="<txp:page_url context="id, s" />">
```
would give you 'canonical' links whatever other parameters (`q`, `pg`, etc) are. But `trim="/"` shouldn't be necessary here.

**Comment by philwareham** [comment] 2019-12-18 12:01
So do I put the code you suggested in, @bloatware ? Or leave as it is now?

**Comment by bloatware** [comment] 2019-12-18 14:40
If everything is working I'd leave it as is :-)

**Comment by philwareham** [comment] 2019-12-18 14:41
OK, closing this one. Thanks all.

**Closed by philwareham** 2019-12-18 14:41 UTC
Labels: Under investigation
